### ISSUE TITLE
should give  download source of the datasets  in /home/jakc4103/WDesktop/dataset/ILSVRC/Data/CLS-LOC/val

### ISSUE THREAD

**Issue by ClarkChin08** [jakc4103/DFQ#13]
in file main_cls.py

**Comment by jakc4103** [comment]
you can download imagenet validation set from [kaggle](https://www.kaggle.com/c/imagenet-object-localization-challenge) or [academictorrents](http://academictorrents.com/browse.php?search=imagenet)

**Comment by ClarkChin08** [comment]
another question is about 16-bits Quantization for Bias, that means the bias is 16-bits? or the weight should be quantized to 16-bits? if the weight was quantized to 16-bits, the accuracy improved may come from the high precision of weight, right?

**Comment by jakc4103** [comment]
weight: 8 bits
activation: 8 bits
bias: 16 bits

All quantization in this repo is per-tensor based.

**Comment by bangawayoo** [comment]
Bias quantized to 8 bits also seems to work fine for me.

**Comment by jakc4103** [comment]
@bangawayoo well, that's good to know! It probably because I've fixed some minor bugs in set_quant_minmax function recently. I'll update the 8 bits results after I test it.
