### ISSUE TITLE
TypeError: new() received an invalid combination of arguments - got (NoneType, NoneType), but expected one of

### ISSUE THREAD

**Issue by drahmad89** [jakc4103/DFQ#23]
I cloned the repo and tried to run the demo but was having this error:

(env) chaahm@HCAPC3612:~/DFQ$ python main_cls.py --quantize --relu --equalize
load weight: modeling/classification/mobilenetv2_1.0-f2a8633.pth.tar
register <class 'torch.nn.modules.conv.Conv2d'> <class 'utils.quantize.QuantNConv2d'>
register <class 'torch.nn.modules.linear.Linear'> <class 'utils.quantize.QuantNLinear'>
Traceback (most recent call last):
  File "main_cls.py", line 214, in <module>
    main()
  File "main_cls.py", line 132, in main
    model, transformer = switch_layers(model, transformer, data, module_dict, ignore_layer=[QuantMeasure], quant_op=args.quantize)
  File "/home/chaahm/DFQ/utils/layer_transform.py", line 157, in switch_layers
    model = transformer.trans_layers(model, update=True if key == 1 else False)
  File "/home/chaahm/DFQ/PyTransformer/transformers/torchTransformer.py", line 84, in trans_layers
    _layer_new = self._register_dict[type(getattr(model, module_name))](**_kwargs) # only give positional args
  File "/home/chaahm/DFQ/utils/quantize.py", line 347, in __init__
    super(QuantNLinear, self).__init__(in_features, out_features, bias)
  File "/home/chaahm/env/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 72, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new() received an invalid combination of arguments - got (NoneType, NoneType), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (NoneType, NoneType)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (NoneType, NoneType)

**Comment by drahmad89** [comment]
After digging in a little bit I found that in PyTransformer the build graph method ignore the data if the layer name has no "feature" or "kernel" string

**Comment by jakc4103** [comment]
Which version of PyTransformer you used?

**Comment by drahmad89** [comment]
I cloned from the master branch!
https://github.com/ricky40403/PyTransformer.git

**Comment by jakc4103** [comment]
Use the hotfix branch (or the commit id shown in DFQ repo) instead; that version is compatible with DFQ implementation.
