### ISSUE TITLE
An error during running 

### ISSUE THREAD

**Issue by nsping13** [jakc4103/DFQ#26]
Hi,
Thanks for sharing!
any idea what is the reason for the following error:
File "DFQ/PyTransformer/transformers/utils.py", line 177, in __getattr__
return object.__getattribute__(self, name)			
AttributeError: 'Log' object has no attribute 'getRecordTensorOP'

Thanks!

**Comment by jakc4103** [comment]
Try the "hotfix" branch of PyTransformer

**Comment by nsping13** [comment]
Same...

**Comment by nsping13** [comment]
now having:
File "/DFQ/utils/layer_transform.py", line 449, in set_quant_minmax
quant_module[0].running_max.fill_(2.64) # use (1 - mean)/std as in data preprocess
TypeError: 'NoneType' object is not subscriptable

**Comment by nsping13** [comment]
It is related to the previous issue, there is some mismatch between the QuantNConv2d, QuantMeasure
