### ISSUE TITLE
Model acc Inquiry

### ISSUE THREAD

**Issue by rematchka** [jakc4103/DFQ#30]
Hi, It is kind of you to share your work.
Very appreciate it.

I have been trying to run this repo mainly layer equalization. However, I've encountered some troubles. The accuracy I keep getting is original model accuracy, as is graph doesn't reflect on the model.
In main_cls.py, I set options to  --relu  --equaliz --correction
Do you have any idea why I keep getting this behavior?

**Comment by jakc4103** [comment]
Perhaps add an additional option '-quantize'

**Comment by rematchka** [comment]
But I don't want to quantize, I want to reproduce the result of using layer equalization for the original model FP32

**Comment by jakc4103** [comment]
What do you mean by 'the graph is not reflecting on the model weight' ?
What is the current results you get? 
With only '-relu -equalize', the FP32 model would get exactly the same accuracy to original one. with additional '-correction', the results might change, depends on the model weight.
And BTW, it does not make sense to apply bias correction on FP32 model.

**Comment by rematchka** [comment]
1- If I plot weights using matplotlib and print weight distribution in the graph from the transformer, in which all transformation is applied as relu, LE,  it's different from the weight in the model variable, which is used for inference.
2- whatever I do to mobilenet v2 model, I always get  71.7 %
3-  According to your results, ReLU+ LE would decrease accuracy by 0.01 or 0.1
4- I was applying bias correction on FP 8 model.

**Comment by jakc4103** [comment]
Could you post code snippet here? on how you plot weight distribution and maybe with the results too.
From the second thing you mentioned, what exactly you did and whats the result w.r.t each setting?

**Comment by rematchka** [comment]
Distribution of weights in the first conv layer in both model and graph
![Screenshot (497)](https://user-images.githubusercontent.com/25964922/107517172-0f4f3080-6bb6-11eb-8628-84cc379bde17.png)
![Screenshot (498)](https://user-images.githubusercontent.com/25964922/107517187-16763e80-6bb6-11eb-8081-aeb5729a0f9c.png)
Analysis of number of unique values per layer for both graph and model
![Screenshot (501)](https://user-images.githubusercontent.com/25964922/107517734-ca77c980-6bb6-11eb-9207-dfadfa929d65.png)
![Screenshot (502)](https://user-images.githubusercontent.com/25964922/107517741-ccda2380-6bb6-11eb-9ba0-7f37f67e12a9.png)
 model accuracy: 71.7%
model + ReLU+LE: 71.7%
model+ RELU+LE+ piece wise quantization 4 bits+ BC: 71.7%

**Comment by jakc4103** [comment]
Could you check whether the weight of first conv layer is the same before/after applying relu,LE?

**Comment by rematchka** [comment]
No they aren't identical
![Screenshot (503)](https://user-images.githubusercontent.com/25964922/107525221-4bd35a00-6bbf-11eb-96e8-ae6e3a381e02.png)
![Screenshot (504)](https://user-images.githubusercontent.com/25964922/107525236-4ece4a80-6bbf-11eb-9557-b9deb9651c64.png)

**Comment by jakc4103** [comment]
I mean, could you use the second method, ie. model.named_parameter to print weight before/after applying any change to model? just to make sure you get the weight from same layer

**Comment by rematchka** [comment]
The weights of the first layer are identical before applying batch norm folding-RLEU-LE and after applying the. I checked it using diff checker also.
![Screenshot (505)](https://user-images.githubusercontent.com/25964922/107616128-1ded2480-6c56-11eb-8fc0-ede1ad31fcfe.png)
![Screenshot (506)](https://user-images.githubusercontent.com/25964922/107616133-204f7e80-6c56-11eb-813b-0930d6318d08.png)

**Comment by jakc4103** [comment]
I have tested, and the code is fine.
While I execute ```python main_cls.py --relu --equalize```
I print out the weight [HERE](https://github.com/jakc4103/DFQ/blob/master/main_cls.py#L150) and [HERE](https://github.com/jakc4103/DFQ/blob/master/main_cls.py#L198), both by ```for name, param in model.named_parameters():```.
For the first layer, I get tensor maximum and minimum value (max_val, min_val) as (0.307, -0.262) before apply LE and (0.856, -0.964) after applying it.

**Comment by rematchka** [comment]
I will try to re-download the repo and reinstall all dependencies, maybe it's the issue

**Comment by rematchka** [comment]
It finally worked. Thank you
