### ISSUE TITLE
cmake error while doing the real int8 inference

### ISSUE THREAD

**Issue by guoyudejin** [jakc4103/DFQ#32]
Hi there, very impressive work!
While implementing your project, I have a little trouble compiling the inference_cls.cpp using the CMakeLists.txt.

**Here is my CMakeLists.txt:**

> cmake_minimum_required(VERSION 2.8.12)
> project(dfq)
> include_directories(/Users/heyiqian/Desktop/EdgeAI/ncnn/src)
> include_directories(/Users/heyiqian/Desktop/EdgeAI/ncnn/build/src)
> 
> #openmp
> FIND_PACKAGE( OpenMP REQUIRED)
> if(OPENMP_FOUND)
>     message("OPENMP FOUND")
>     set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
>     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
>     set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
> endif()
> 
> #ncnn
> set(NCNN_LIBS /Users/heyiqian/Desktop/EdgeAI/ncnn/build/install/lib/libncnn.a)
> set(NCNN_INCLUDE_DIRS /Users/heyiqian/Desktop/EdgeAI/ncnn/build/install/include)
> include_directories(${NCNN_INCLUDE_DIRS})
> 
> #opencv
> find_package( OpenCV REQUIRED )
> include_directories( ${OpenCV_INCLUDE_DIRS} )
> 
> add_executable(inference_cls inference_cls.cpp)
> target_link_libraries(inference_cls ${NCNN_LIBS})
> target_link_libraries( inference_cls ${OpenCV_LIBS} )
> target_link_libraries(${PROJECT_NAME} ${OpenMP_CXX_LIBRARIES})

 **Here is my cmake command:**
> cmake -DCMAKE_C_COMPILER="/usr/local/Cellar/llvm/11.1.0/bin/clang" -> 
> DCMAKE_CXX_COMPILER="/usr/local/Cellar/llvm/11.1.0/bin/clang++" ..

**And this is what I get from the CMakeError.log(parts of it, others are similar to the following ones):**

> Detecting C OpenMP failed with the following output:
> Change Dir: /Users/heyiqian/Desktop/EdgeAI/DFQ-master/build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/make cmTC_367b0/fast && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_367b0.dir/build.make CMakeFiles/cmTC_367b0.dir/build
> Building C object CMakeFiles/cmTC_367b0.dir/OpenMPTryFlag.c.o
> /usr/local/Cellar/llvm/11.1.0/bin/clang   -fopenmp=libomp -v -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.15 -o CMakeFiles/cmTC_367b0.dir/OpenMPTryFlag.c.o -c /Users/heyiqian/Desktop/EdgeAI/DFQ-master/build/CMakeFiles/FindOpenMP/OpenMPTryFlag.c
> clang version 11.1.0
> Target: x86_64-apple-darwin19.6.0
> Thread model: posix
> InstalledDir: /usr/local/Cellar/llvm/11.1.0/bin
>  (in-process)
>  "/usr/local/Cellar/llvm/11.1.0/bin/clang-11" -cc1 -triple x86_64-apple-macosx10.15.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name OpenMPTryFlag.c -mrelocation-model pic -pic-level 2 -mframe-pointer=all -fno-rounding-math -munwind-tables -target-sdk-version=11.0 -fcompatibility-qualified-id-block-type-checking -target-cpu penryn -debugger-tuning=lldb -target-linker-version 609.8 -v -resource-dir /usr/local/Cellar/llvm/11.1.0/lib/clang/11.1.0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/local/include -internal-isystem /usr/local/Cellar/llvm/11.1.0/lib/clang/11.1.0/include -internal-externc-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -fdebug-compilation-dir /Users/heyiqian/Desktop/EdgeAI/DFQ-master/build/CMakeFiles/CMakeTmp -ferror-limit 19 -fopenmp -fopenmp-cuda-parallel-target-regions -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fmax-type-align=16 -o CMakeFiles/cmTC_367b0.dir/OpenMPTryFlag.c.o -x c /Users/heyiqian/Desktop/EdgeAI/DFQ-master/build/CMakeFiles/FindOpenMP/OpenMPTryFlag.c
> clang -cc1 version 11.1.0 based upon LLVM 11.1.0 default target x86_64-apple-darwin19.6.0
> ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/local/include"
> ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/Library/Frameworks"
> #include "..." search starts here:
> #include <...> search starts here:
>  /usr/local/Cellar/llvm/11.1.0/lib/clang/11.1.0/include
>  /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include
>  /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks (framework directory)
> End of search list.
> Linking C executable cmTC_367b0
> /usr/local/Cellar/cmake/3.19.6/bin/cmake -E cmake_link_script CMakeFiles/cmTC_367b0.dir/link.txt --verbose=1
> /usr/local/Cellar/llvm/11.1.0/bin/clang  -fopenmp=libomp -v -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.15 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_367b0.dir/OpenMPTryFlag.c.o -o cmTC_367b0  -v -Wl,-v 
> clang version 11.1.0
> Target: x86_64-apple-darwin19.6.0
> Thread model: posix
> InstalledDir: /usr/local/Cellar/llvm/11.1.0/bin
>  "/usr/bin/ld" -demangle -lto_library /usr/local/Cellar/llvm/11.1.0/lib/libLTO.dylib -dynamic -arch x86_64 -platform_version macos 10.15.0 11.0 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -o cmTC_367b0 -search_paths_first -headerpad_max_install_names CMakeFiles/cmTC_367b0.dir/OpenMPTryFlag.c.o -v -lomp -lSystem /usr/local/Cellar/llvm/11.1.0/lib/clang/11.1.0/lib/darwin/libclang_rt.osx.a
> @(#)PROGRAM:ld  PROJECT:ld64-607.2
> BUILD 04:30:50 Jul 14 2020
> configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
> Library search paths:
> 	/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib
> Framework search paths:
> 	/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/
> ld: library not found for -lomp
> clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [cmTC_367b0] Error 1
> make: *** [cmTC_367b0/fast] Error 2
> 
> Detecting CXX OpenMP failed with the following output:
> Change Dir: /Users/heyiqian/Desktop/EdgeAI/DFQ-master/build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/make cmTC_2a53f/fast && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_2a53f.dir/build.make CMakeFiles/cmTC_2a53f.dir/build
> Building CXX object CMakeFiles/cmTC_2a53f.dir/OpenMPTryFlag.cpp.o
> /usr/local/Cellar/llvm/11.1.0/bin/clang++   -Xclang -fopenmp -v -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.15 -o CMakeFiles/cmTC_2a53f.dir/OpenMPTryFlag.cpp.o -c /Users/heyiqian/Desktop/EdgeAI/DFQ-master/build/CMakeFiles/FindOpenMP/OpenMPTryFlag.cpp
> clang version 11.1.0
> Target: x86_64-apple-darwin19.6.0
> Thread model: posix
> InstalledDir: /usr/local/Cellar/llvm/11.1.0/bin
>  (in-process)
>  "/usr/local/Cellar/llvm/11.1.0/bin/clang-11" -cc1 -triple x86_64-apple-macosx10.15.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name OpenMPTryFlag.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=all -fno-rounding-math -munwind-tables -target-sdk-version=11.0 -fcompatibility-qualified-id-block-type-checking -target-cpu penryn -debugger-tuning=lldb -target-linker-version 609.8 -v -resource-dir /usr/local/Cellar/llvm/11.1.0/lib/clang/11.1.0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -stdlib=libc++ -internal-isystem /usr/local/Cellar/llvm/11.1.0/bin/../include/c++/v1 -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include/c++/v1 -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/local/include -internal-isystem /usr/local/Cellar/llvm/11.1.0/lib/clang/11.1.0/include -internal-externc-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -fdeprecated-macro -fdebug-compilation-dir /Users/heyiqian/Desktop/EdgeAI/DFQ-master/build/CMakeFiles/CMakeTmp -ferror-limit 19 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fopenmp -o CMakeFiles/cmTC_2a53f.dir/OpenMPTryFlag.cpp.o -x c++ /Users/heyiqian/Desktop/EdgeAI/DFQ-master/build/CMakeFiles/FindOpenMP/OpenMPTryFlag.cpp
> clang -cc1 version 11.1.0 based upon LLVM 11.1.0 default target x86_64-apple-darwin19.6.0
> ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include/c++/v1"
> ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/local/include"
> ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/Library/Frameworks"
> #include "..." search starts here:
> #include <...> search starts here:
>  /usr/local/Cellar/llvm/11.1.0/bin/../include/c++/v1
>  /usr/local/Cellar/llvm/11.1.0/lib/clang/11.1.0/include
>  /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include
>  /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks (framework directory)
> End of search list.
> Linking CXX executable cmTC_2a53f
> /usr/local/Cellar/cmake/3.19.6/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2a53f.dir/link.txt --verbose=1
> /usr/local/Cellar/llvm/11.1.0/bin/clang++  -Xclang -fopenmp -v -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.15 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_2a53f.dir/OpenMPTryFlag.cpp.o -o cmTC_2a53f  -v -Wl,-v 
> clang version 11.1.0
> Target: x86_64-apple-darwin19.6.0
> Thread model: posix
> InstalledDir: /usr/local/Cellar/llvm/11.1.0/bin
>  "/usr/bin/ld" -demangle -lto_library /usr/local/Cellar/llvm/11.1.0/lib/libLTO.dylib -dynamic -arch x86_64 -platform_version macos 10.15.0 11.0 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -o cmTC_2a53f -search_paths_first -headerpad_max_install_names CMakeFiles/cmTC_2a53f.dir/OpenMPTryFlag.cpp.o -v -lc++ -lSystem /usr/local/Cellar/llvm/11.1.0/lib/clang/11.1.0/lib/darwin/libclang_rt.osx.a
> @(#)PROGRAM:ld  PROJECT:ld64-607.2
> BUILD 04:30:50 Jul 14 2020
> configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
> Library search paths:
> 	/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib
> Framework search paths:
> 	/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/
> Undefined symbols for architecture x86_64:
>   "_omp_get_max_threads", referenced from:
>       _main in OpenMPTryFlag.cpp.o
> ld: symbol(s) not found for architecture x86_64
> clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [cmTC_2a53f] Error 1
> make: *** [cmTC_2a53f/fast] Error 2

I've tried lots of methods from google to fix this, but none of them work. 
Any suggestions may be helpful, looking forward for your reply!

**Comment by jakc4103** [comment]
```ld: library not found for -lomp```
Seem some library are not found.
