### ISSUE TITLE
How to get symmetric quantization (int8') result?

### ISSUE THREAD

**Issue by suwaxu** [jakc4103/DFQ#35]
I am wondering how I can get the symmetric quantization (int8') result. I tried to set symmetric=True in the forward function if UniformQuantize class, however I got a different number. In RELU+LE case, I got 66.89. Any help will be appreciated.

**Comment by jakc4103** [comment]
Just set [```quantize``` function](https://github.com/jakc4103/DFQ/blob/master/utils/quantize.py#L86) with symmetric=True for both parameters and activations.
The reported results might be slightly different due to code updates. I'll check the numbers.

**Comment by suwaxu** [comment]
> Just set [`quantize` function](https://github.com/jakc4103/DFQ/blob/master/utils/quantize.py#L86) with symmetric=True for both parameters and activations.
> The reported results might be slightly different due to code updates. I'll check the numbers.

Thanks so much!
