### ISSUE TITLE
exported quantized network via onnx to MNN/CoreML

### ISSUE THREAD

**Issue by dragen1860** [jakc4103/DFQ#36]
Dear author:
  Thanks for sharing this great work! 
   is this quantization technology able to quantize any pretrained cnn network? I tried your code and able to export to ncnn model. But I also intereseted in export it for coreml/MNN model. Could you give some tips?

**Comment by jakc4103** [comment]
There are several resources on the internet about converting onnx model to MNN/coreml models.
I did not try any, but you could start there.
