### ISSUE TITLE
Accuracy drop after bias correction

### ISSUE THREAD

**Issue by cyshih73** [jakc4103/DFQ#39]
Hi author,

Here is the result when I run the code:
- python main_cls.py --quantize --relu --equalize: 0.6865
- python main_cls.py --quantize --relu --equalize --correction: 0.68072

With training
- python main_cls.py --quantize --relu --equalize --trainable: 0.6873
- python main_cls.py --quantize --relu --equalize --trainable --correction: 0.68186

The accuracy dropped after bias correction. I took a look at the code, where the num_bits_bias is by default 16, which should be "Int8**" in the Readme.

Any suggestion on how could I make the accuracy after bias correction better? Thank you for the great work!

**Comment by jakc4103** [comment]
The default bias bits is defined [HERE](https://github.com/jakc4103/DFQ/blob/master/main_cls.py#L38), which is 8 bits.

**Comment by cyshih73** [comment]
Ahh, I misread that part of the code.
After add the --bits_bias 16 argument, the accuracy become (no correction: correction) (0.7024: 0.7083)
Thank you so much for your answer!
