### ISSUE TITLE
weight symmetric quantization seems unworkable

### ISSUE THREAD

**Issue by evi-Genius** [jakc4103/DFQ#4]
Hi. I want to get the result of weight symmetric quantization. So I set the `symmetric=True` in the function `forward` of class` QuantConv2d`, but it cause error 
:AttributeError: 'float' object has no attribute 'cur_tensor'
So I change the code `max_value = torch.max(torch.abs(max_value), torch.abs(min_value))` 
to `max_value = max(abs(max_value), abs(min_value))`, it's worked, but the acc result is **zero**. I don't understand why, do you have any idea?
I would be grateful if you could solve my question

**Comment by jakc4103** [comment]
yeah, i found that the computation of symmetric quantization is wrong. I'll fix it in the next version.
You can change the code in UniformQuantize.forward to:
```
if symmetric:
    qmin = -2. ** (num_bits - 1)
    qmax = 2 ** (num_bits - 1) - 1
    max_value = abs(max_value)
    min_value = abs(min_value)
    if max_value > min_value:
        scale = max_value / qmax
    else:
        max_value = min_value
        scale = max_value / (qmax + 1)
                
    min_value = 0.

else:
    qmin = 0.
    qmax = 2. ** num_bits - 1.

    scale = (max_value - min_value) / (qmax - qmin)
```

**Comment by evi-Genius** [comment]
> yeah, i found that the computation of symmetric quantization is wrong. I'll fix it in the next version.
> You can change the code in UniformQuantize.forward to:
> 
> ```
> if symmetric:
>     qmin = -2. ** (num_bits - 1)
>     qmax = 2 ** (num_bits - 1) - 1
>     max_value = abs(max_value)
>     min_value = abs(min_value)
>     if max_value > min_value:
>         scale = max_value / qmax
>     else:
>         max_value = min_value
>         scale = max_value / (qmax + 1)
>                 
>     min_value = 0.
> 
> else:
>     qmin = 0.
>     qmax = 2. ** num_bits - 1.
> 
>     scale = (max_value - min_value) / (qmax - qmin)
> ```

Thank you for your reply! I have tested the result of weight symmetic quantization and the acc is 67.1%, looks pretty good.
