### ISSUE TITLE
Could you explain the variable 'data' in main_cls.py line 77. Thanks.

### ISSUE THREAD

**Issue by EdwardLiuYu** [jakc4103/DFQ#6]

**Comment by jakc4103** [comment]
It's a dummy input for PyTransformer to build model graph. You can change it to whatever you want with dimensions 4 (batch, channel, height width) .

**Comment by EdwardLiuYu** [comment]
Ok, I got it. Thanks a lot.


| |
刘子力
|
|
nmliuzili@163.com
|
签名由网易邮箱大师定制


On 12/16/2019 11:35，jakc4103<notifications@github.com> wrote：

It's a dummy input for PyTransformer to build model graph. You can change it to whatever you want with dimensions 4 (batch, channel, height width) .

**Comment by EdwardLiuYu** [comment]
Sorry for bother you again. I don’t understand the operation in relation.py line61-78. And why some relations are deleted from ’tmp’?


| |
刘子力
|
|
nmliuzili@163.com
|
签名由网易邮箱大师定制


On 12/16/2019 11:36，刘子力<nmliuzili@163.com> wrote：
Ok, I got it. Thanks a lot.


| |
刘子力
|
|
nmliuzili@163.com
|
签名由网易邮箱大师定制


On 12/16/2019 11:35，jakc4103<notifications@github.com> wrote：

It's a dummy input for PyTransformer to build model graph. You can change it to whatever you want with dimensions 4 (batch, channel, height width) .

**Comment by jakc4103** [comment]
> Sorry for bother you again. I don’t understand the operation in relation.py line61-78. And why some relations are deleted from ’tmp’? | | 刘子力 | | nmliuzili@163.com | 签名由网易邮箱大师定制 On 12/16/2019 11:36，刘子力<nmliuzili@163.com> wrote： Ok, I got it. Thanks a lot. | | 刘子力 | | nmliuzili@163.com | 签名由网易邮箱大师定制 On 12/16/2019 11:35，jakc4103<notifications@github.com> wrote： It's a dummy input for PyTransformer to build model graph. You can change it to whatever you want with dimensions 4 (batch, channel, height width) . — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I apply layer equalization to those at least 3 consecutive conv_layers are connected without branching. Since there is no such structure in segmentation and classification model, It only affect ssd model (which i am currently testing).

**Comment by EdwardLiuYu** [comment]
Thanks for your answer. I have learned.


| |
刘子力
|
|
邮箱：nmliuzili@163.com
|

签名由 网易邮箱大师 定制

On 12/16/2019 18:24, jakc4103 wrote:

Sorry for bother you again. I don’t understand the operation in relation.py line61-78. And why some relations are deleted from ’tmp’? | | 刘子力 | | nmliuzili@163.com | 签名由网易邮箱大师定制 On 12/16/2019 11:36，刘子力nmliuzili@163.com wrote： Ok, I got it. Thanks a lot. | | 刘子力 | | nmliuzili@163.com | 签名由网易邮箱大师定制 On 12/16/2019 11:35，jakc4103notifications@github.com wrote： It's a dummy input for PyTransformer to build model graph. You can change it to whatever you want with dimensions 4 (batch, channel, height width) . — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I apply layer equalization to those at least 3 consecutive conv_layers are connected without branching. Since there is no such structure in segmentation and classification model, It only affect ssd model (which i am currently testing).
