### ISSUE TITLE
QuantNConv2d won't quantize weight?

### ISSUE THREAD

**Issue by z13974509906** [jakc4103/DFQ#7]
QuantNConv2d will be use if trainale if false. 
![image](https://user-images.githubusercontent.com/20511825/71456350-faf27d80-27d3-11ea-8a74-96fdfb6621ee.png)
But I don't see weigth quantization operator in the layer.
When trainable is false, only quantize input？

**Comment by jakc4103** [comment]
QuantNConv2d is used with [quantize_targ_layer](https://github.com/jakc4103/DFQ/blob/master/utils/layer_transform.py#L279), so parameter quantize is not needed during inference.

Use trainable=True (QuantConv2d) if you need to train the quantized model with straight-through-estimator; but it's a bit slower.

**Comment by z13974509906** [comment]
> QuantNConv2d is used with [quantize_targ_layer](https://github.com/jakc4103/DFQ/blob/master/utils/layer_transform.py#L279), so parameter quantize is not needed during inference.
> 
> Use trainable=True (QuantConv2d) if you need to train the quantized model with straight-through-estimator; but it's a bit slower.

thanks for your reply, another question: only add the option "--quantize", is it quantize the whole conv weight by a scale instead of per channel?(do this in class UniformQuantize(InplaceFunction))

**Comment by jakc4103** [comment]
> thanks for your reply, another question: only add the option "--quantize", is it quantize the whole conv weight by a scale instead of per channel?(do this in class UniformQuantize(InplaceFunction))

UniformQuantize is per-tensor quantization, which means there is only one scale value for whole tensor.

**Comment by z13974509906** [comment]
> > thanks for your reply, another question: only add the option "--quantize", is it quantize the whole conv weight by a scale instead of per channel?(do this in class UniformQuantize(InplaceFunction))
> 
> UniformQuantize is per-tensor quantization, which means there is only one scale value for whole tensor.

got it , thanks!
