### ISSUE TITLE
cross conv branches layer equalization

### ISSUE THREAD

**Issue by georgetseng1128** [jakc4103/DFQ#9]
Hi,

In mobilenetv2_ssd, how do you cross conv branches layer equalization, e.g this figure
![image](https://user-images.githubusercontent.com/51855552/72305106-ac871f00-36ad-11ea-9090-ab8b92865967.png)

**Comment by jakc4103** [comment]
Well, I just skip these layers. I only apply cross layer equalization to conv and linear layers without branching.

**Comment by georgetseng1128** [comment]
Thanks for your reply.
